export const ErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  PLATFORM_AUTH_EXPIRED: 'PLATFORM_AUTH_EXPIRED',
  CONNECTOR_UNAVAILABLE: 'CONNECTOR_UNAVAILABLE',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

